# Simple table parsing in three lines of code

**problem** we have a table of the top 500 computers that we don't want to copy and paste in the following website: https://www.top500.org/lists/top500/2020/11/

In [2]:
# Here's the code in python 3

#Import packages
import pandas as pd

#define url and parse
my_url="https://www.top500.org/lists/top500/2020/11/"
list_of_data_frames = pd.read_html(my_url)

#Print the first table
list_of_data_frames[0]

,Rank,System,Cores,Rmax (TFlop/s),Rpeak (TFlop/s),Power (kW)
0,1,"Supercomputer Fugaku - Supercomputer Fugaku, A...",7630848,442010.0,537212.0,29899.0
1,2,"Summit - IBM Power System AC922, IBM POWER9 22...",2414592,148600.0,200794.9,10096.0
2,3,"Sierra - IBM Power System AC922, IBM POWER9 22...",1572480,94640.0,125712.0,7438.0
3,4,"Sunway TaihuLight - Sunway MPP, Sunway SW26010...",10649600,93014.6,125435.9,15371.0
4,5,"Selene - NVIDIA DGX A100, AMD EPYC 7742 64C 2....",555520,63460.0,79215.0,2646.0
5,6,"Tianhe-2A - TH-IVB-FEP Cluster, Intel Xeon E5-...",4981760,61444.5,100678.7,18482.0
6,7,"JUWELS Booster Module - Bull Sequana XH2000 , ...",449280,44120.0,70980.0,1764.0
7,8,"HPC5 - PowerEdge C4140, Xeon Gold 6252 24C 2.1...",669760,35450.0,51720.8,2252.0
8,9,"Frontera - Dell C6420, Xeon Platinum 8280 28C ...",448448,23516.4,38745.9,NaN
9,10,"Dammam-7 - Cray CS-Storm, Xeon Gold 6248 20C 2...",672520,22400.0,55423.6,NaN

In [5]:
# export to csv
list_of_data_frames[0].to_csv('data.csv')